server:
    port: 8080
eureka:
   client:
      service-url:
       defaultZone: http://localhost:8761/eureka/

spring:
 application:
  name: ApiGateWayForService
 cloud:
    gateway:
      routes:
      - id: CrickPlayersApplicationAdmin
        uri: http://localhost:8082/
        predicates: 
        - Path=/api/v1/**
      - id: CrickPlayersApplicationUser
        uri: http://localhost:8083/
        predicates:
        - Path=/api/v1/**
      - id: Cricket_Player_App_JWT_Service
        uri: http://localhost:8081/
        predicates:
        - Path=/api/jwt/**
          
        
  