jwt:
  secret: secrectkey123

server:
    port: 8081         
    
    
spring:
    application:
           name: Cricket_Player_App_JWTService
    data:
        mongodb:
            uri: mongodb+srv://Saket:shri1008@cluster0.zbqa4.mongodb.net/PlayerDB?retryWrites=true&w=majority
             
eureka:
     client:
          service-url:
                   defaultZone: http://localhost:8761/eureka/          
                          
logging:
  file: 
    path: /my-logs/app.log
    name: log.txt  
    
data:
   exception:
          incmsg: Invalid Credentials!!
            